apiVersion: v1
kind: Secret
metadata:
  name: sbms-gateway-secret
  namespace: sbms
type: Opaque
stringData:
  SBMS_JWT_SECRET: "S2JQZVNoVm1ZcTN0Nnc5eiRDJkUpSEBNY1FmVGpXblo="  # set this to same secret used by sbms-backend when issuing HS256 tokens

