apiVersion: v1
kind: Service
metadata:
  name: sbms-gateway
  namespace: sbms
spec:
  type: ClusterIP
  selector:
    app: sbms-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080

