apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbms-gateway
  namespace: sbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbms-gateway
  template:
    metadata:
      labels:
        app: sbms-gateway
    spec:
      containers:
        - name: sbms-gateway
          image: sbms-gateway:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

