pring:
  application:
    name: sbms-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/smart-board
    username: smartboard_admin
    password: "09090909" # Quoted to prevent parsing as octal/number if it starts with 0
    
  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true