spring:
  application:
    name: sbms-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-board
    username: smartboard_admin
    password: "09090909"
    driver-class-name: org.postgresql.Driver
    # The 'hikari' block and its properties must be properly indented under 'datasource'.
    hikari:
      # THIS LINE MUST USE SPACES FOR INDENTATION
      max-lifetime: 300000

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Mail / SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thareesha01@gmail.com
    password: foewigznsutmonhm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Multipart File Upload Settings
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


aws:
  #accessKeyId: AKIA2AUOOUX3O5UUUYBN      # replace after regenerating
  #secretAccessKey: E+85hlGWYo8pT9ECKNY+2YGUkJ0hzf4jBqAJngpb  # replace after regenerating
  region: ap-south-1
  s3:
    bucketName: smart-board-project


#url: jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/smart-board