apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbms-backend
  namespace: sbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbms-backend
  template:
    metadata:
      labels:
        app: sbms-backend   # ðŸ‘ˆ IMPORTANT LABEL
    spec:
      containers:
        - name: sbms-backend
          image: sbms-backend:1.0   # from your Docker build
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

