apiVersion: v1
kind: Service
metadata:
  name: sbms-backend
  namespace: sbms
spec:
  selector:
    app: sbms-backend      # ðŸ‘ˆ MUST MATCH Deployment label
  ports:
    - port: 8080           # service port (inside cluster)
      targetPort: 8080     # containerPort from Deployment
  type: ClusterIP

