apiVersion: v1
kind: Service
metadata:
  name: sbms-backend
  namespace: sbms
spec:
  type: NodePort     # ‚Üê YOU MISSED THIS LINE
  selector:
    app: sbms-backend
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30086   # valid only when type = NodePort

