apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbms-backend
  namespace: sbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbms-backend
  template:
    metadata:
      labels:
        app: sbms-backend # ðŸ‘ˆ IMPORTANT LABEL
    spec:
      containers:
        - name: sbms-backend
          image: sbms-backend:2.0 # from your Docker build
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: sbms-db-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sbms-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sbms-db-secret
                  key: password
