apiVersion: v1
kind: Secret
metadata:
  name: sbms-db-secret
  namespace: sbms
type: Opaque
data:
  username: c21hcnRib2FyZF9hZG1pbg==      # base64("postgres")
  password: MDkwOTA5MDk=      # base64("password")

