apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appointment-service-k8s-reader-binding
  namespace: sbms
subjects:
  - kind: ServiceAccount
    name: appointment-service-sa
    namespace: sbms
roleRef:
  kind: Role
  name: appointment-service-k8s-reader
  apiGroup: rbac.authorization.k8s.io

