apiVersion: v1
kind: ConfigMap
metadata:
  name: sbms-appointment-db-config
  namespace: sbms
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/sbms_appointment_db
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

  # RabbitMQ (same as other services)
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"

  # Event exchange (MUST MATCH notification-service)
  SBMS_RABBITMQ_EXCHANGE: sbms.events

