apiVersion: v1
kind: Secret
metadata:
  name: sbms-appointment-db-secret
  namespace: sbms
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: YXBwb2ludG1lbnRfdXNlcg==        # base64("postgres")
  SPRING_DATASOURCE_PASSWORD: YXBwb2ludG1lbnQwOTA5MDkwOQ==  # base64("postgres")

