server:
  port: 8085

spring:
  application:
    name: sbms-notification-service

  datasource:
    url: jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/sbms_notification_db
    username: notification_user
    password: notification09090909

  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange: sbms.events
  queue: sbms.notification.queue
  routing-key: notification.#

  
security:
  jwt:
    jwk-set-uri: http://localhost:8081/.well-known/jwks.json
