apiVersion: v1
kind: Service
metadata:
  name: sbms-notification-service
  namespace: sbms
spec:
  selector:
    app: sbms-notification-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP

