apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sbms-notification-k8s-reader-binding
  namespace: sbms
subjects:
  - kind: ServiceAccount
    name: sbms-notification-service-sa
    namespace: sbms
roleRef:
  kind: Role
  name: sbms-notification-k8s-reader
  apiGroup: rbac.authorization.k8s.io

