apiVersion: v1
kind: Secret
metadata:
  name: sbms-notification-db-secret
  namespace: sbms
type: Opaque
data:
  username: bm90aWZpY2F0aW9uX3VzZXI=      # base64("postgres")
  password: bm90aWZpY2F0aW9uMDkwOTA5MDk=      # base64("password")

